#Installer File for Application_Dashboard.R
install.packages("shiny")
install.packages("shinydashboard")
install.packages("choroplethr")
install.packages("choroplethrMaps")
install.packages("leaflet")
install.packages("geojsonio")
install.packages("dplyr")
install.packages("stringr")
install.packages("ggplot2")
install.packages("plotly")
install.packages("DT")
install.packages("broom")
install.packages("readxl")